[tasks.export-openapi]
description = "Write API Server: OpenAPI定義内容をエクスポートします"
workspace = false
script = """
if exist ..\\frontend\\schemas\\openapi.yaml del ..\\frontend\\schemas\\openapi.yaml /q
if not exist ..\\frontend\\schemas mkdir ..\\frontend\\schemas
cargo run -p write-api-server --bin export-openapi-yaml > ..\\frontend\\schemas\\openapi.yaml
"""

[tasks.export-sdl]
description = "Read API Server: GraphQLのSDLをエクスポートします"
workspace = false
script = """
if exist ..\\frontend\\schemas\\schema.graphql del ..\\frontend\\schemas\\schema.graphql /q
if not exist ..\\frontend\\schemas mkdir ..\\frontend\\schemas
cargo run -p read-api-server --bin export-sdl > ..\\frontend\\schemas\\schema.graphql
"""

[tasks.export-all]
description = "OpenAPI定義とGraphQLのSDLをエクスポートします"
workspace = false
script = """
cargo make export-openapi
cargo make export-sdl
"""

[tasks.build-write-server]
description = "Write API Serverをビルドします"
workspace = false
script = """
cargo lambda build --release -p write-api-server --bin write-api-server
"""

[tasks.run-write-server]
description = "Write API Serverを実行します"
workspace = false
script = """
cargo run -p write-api-server --bin write-api-server
"""

[tasks.build-read-server]
description = "Read API Serverをビルドします"
workspace = false
script = """
cargo build --release -p read-api-server --bin read-api-server
"""

[tasks.run-read-server]
description = "Read API Serverを実行します"
workspace = false
script = """
cargo run -p read-api-server --bin read-api-server
"""
